### ISSUE TITLE
v20230404 memory and CPU usage spike

### ISSUE THREAD

**Issue by mosajjal** [txthinking/brook#1158]
After upgrading to v20230404 and enabling prometheus, both CPU and RAM usage are very high compared to what it was before:

![image](https://user-images.githubusercontent.com/10158936/228152969-d9bbf947-7223-4bde-b08c-aa4689944ca9.png)

any ideas?

**Comment by mosajjal** [comment]
a few days later, seems like turning off Prometheus endpoint will solve the issue:

![image](https://user-images.githubusercontent.com/10158936/229340812-840e397d-044a-4820-bca9-72b2d7047ed3.png)

**Comment by txthinking** [comment]
Two possible reasons
- one is that [github.com/prometheus/client_golang](https://github.com/txthinking/brook/blob/master/plugins/prometheus/prometheus.go#L22) does require more content and CPU
- one is that the way [it is used](https://github.com/txthinking/brook/blob/master/plugins/prometheus/prometheus.go) is not best practice. It's actually just a few lines of code.

Because my situation is that there are not many requests, I don't feel much difference. But you can use go tool pproff to assist judgment.

**Comment by mosajjal** [comment]
yep will do. I'll do more tests and will let you know.

**Comment by mosajjal** [comment]
had to switch to REALITY because the rest are getting blocked by the FW so didn't get to actually do meaningful benchmark with high traffic :( closing this
