### ISSUE TITLE
Could you update live.com in PAC?

### ISSUE THREAD

**Issue by wilber822** [txthinking/brook#276]
#### Describe actual behavior
Cannot access *.live.com with Brook.

#### What is your expected behavior
Access *.live.com by Brook PAC mode.

#### Specifications like the version of the project, operating system, or hardware
Windows 10

#### Steps to deploy the server
N/A

#### Steps to reproduce the problem
1. Open onedrive.live.com

**Comment by txthinking** [comment]
Yes, live.com is in white list. https://github.com/txthinking/pac/blob/master/white.list#L6106

Do we need to move it to black list?

**Comment by wilber822** [comment]
@txthinking , I tried "PAC" and "White list" both on Windows 10. Still cannot open *.live.com.
Can you?

**Comment by txthinking** [comment]
### MacOS/Windows GUI client

`White List`
If your request domain is in `the domain list url you entered` or request IP is in `the CIDR list url you entered`, then it will be directly connected. Otherwise, it will go through the proxy.

`Black List`
If your request domain is in `the domain list url you entered` or request IP is in `the CIDR list url you entered`, then it will go through the proxy. Otherwise, it will be directly connected

`PAC`
Your PAC, you control the rule.

`Manual `
Brook only start proxy, you control how to use it.

### iOS GUI client

`White List`
If your request domain is in `the builtin white domain list url` or request IP is in `the builtin white CIDR list url`, then it will be directly connected. Otherwise, it will go through the proxy.

`Black List`
If your request domain is in `the builtin black domain list url` or request IP is in `the builtin black CIDR list url`, then it will go through the proxy. Otherwise, it will be directly connected


For your problem, if you are using `https://www.txthinking.com/pac/white.list`(open sourced on https://github.com/txthinking/pac), you can submit a PR to remove live.com from white.list

**Comment by wilber822** [comment]
Hi @txthinking 
Done. I'm not a developer, not familiar with GitHub. I hope I did correctly. :-)

**Comment by txthinking** [comment]
Good work.

Your PR has been merged https://github.com/txthinking/pac/pull/10

**Comment by dwsr36** [comment]
Hello everyone,

I don't think it is the best solution. The login IP will changes to the proxy now and microsoft will recognize me as "unusual sign-in".

Therefore, I prefer to add "login.live.com" into whitelist.

Different opinions are welcome.

**Comment by dwsr36** [comment]
This will happen if a person has logged in the microsoft account in windows, and he or she also logged in microsoft services in a web browser through brook.

Furthermore, only if login.live.com were redirected to other website, I prefer to remove it out of the whitelist.

**Comment by txthinking** [comment]
@dwsr36 Please PR it if no one has disagreement :)
