### ISSUE TITLE
请问如何以go get方式编译

### ISSUE THREAD

**Issue by Shadowhack0419** [txthinking/brook#46]
好像go get以后不会生成可执行文件请问如何操作？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Shadowhack0419** [comment]
还有请问music是什么东东

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Shadowhack0419** [comment]
还有就是如果能和ss一样支持udp的话那就完全超越ss了抗干扰很强(PS:人用的不多还没被怼到/滑稽/)

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by txthinking** [comment]
请提供
os相关信息
操作步骤


On Aug 2, 2017 23:47, "ShadowhackV" <notifications@github.com> wrote:

还有就是如果能和ss一样支持udp的话那就完全超越ss了抗干扰很强(PS:人用的不多还没被怼到/滑稽/)

*Sent from my Xiaomi MI 5 using FastHub
<https://play.google.com/store/apps/details?id=com.fastaccess.github>*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/txthinking/brook/issues/46#issuecomment-319713651>, or mute
the thread

**Comment by txthinking** [comment]
`$ go get github.com/txthinking/brook/cli/brook`

**Comment by Shadowhack0419** [comment]
@txthinking 但是好像不会生成可执行文件。。。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
