### ISSUE TITLE
How to set global proxy and pac proxy

### ISSUE THREAD

**Issue by Ericliu68** [txthinking/brook#591]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Discussion

windows 64 , I did not find how to set Proxy mode

**Comment by ylfzq** [comment]
Windows 64 is not an operating system. But I guess you are using Windows 10 x64 version. You can use GUI client instead of cli one, it will set-up all for you.

If you really want to set by yourself. Try this:
![image](https://user-images.githubusercontent.com/8508493/65755956-b27ce280-e146-11e9-829c-121bb5c1de2a.png)
![image](https://user-images.githubusercontent.com/8508493/65755988-c6c0df80-e146-11e9-8d92-72ff72137607.png)
![image](https://user-images.githubusercontent.com/8508493/65756040-dfc99080-e146-11e9-877c-88cbc1952994.png)

I hope you don't need further help.

**Comment by Weiged** [comment]
proxifier is an option
