### ISSUE TITLE
Brook 服务端实现缺陷可能导致主动探测

### ISSUE THREAD

**Issue by studentmain** [txthinking/brook#708]
# Brook 服务端实现缺陷可能导致主动探测

**注意：并非协议设计缺陷，此缺陷可以通过软件更新修复，请勿恐慌**

## 方法

在到 Brook 服务端的 TCP 连接上逐字节发送随机数，连接会在服务端接收到第 30 字节时断开。

### 附 PoC 源代码

命令行参数：`main.exe [服务器地址 [测量次数]]`，服务器地址默认 `127.0.0.1:8388`，测量次数默认 16 次

如果怀疑是 Brook 服务端，则会输出 `brook true`，反之输出 `brook false`

``` go
package main

import (
	"log"
	"math/rand"
	"net"
	"os"
	"strconv"
	"sync"
	"time"
)

func test(ep string) int {
	conn, err := net.Dial("tcp", ep)
	if err != nil {
		log.Panicln("dial:", err)
	}
	defer conn.Close()
	buf := make([]byte, 1)

	for i := 0; i < 256; i++ {
		buf[0] = byte(rand.Intn(256))
		n, err := conn.Write(buf)
		if err != nil || n != 1 {
			log.Println("error at", i)
			return i
		}
		time.Sleep(10 * time.Millisecond)
	}
	return 99999
}

func main() {
	fuck := true

	target := "127.0.0.1:8388"
	if len(os.Args) >= 2 {
		target = os.Args[1]
	}

	count := 16
	if len(os.Args) >= 3 {
		var e error
		if count, e = strconv.Atoi(os.Args[2]); e != nil {
			log.Fatalln(e)
		}
	}

	var wg sync.WaitGroup
	wg.Add(count)
	for i := 0; i < count; i++ {
		go func() {
			defer wg.Done()
			if test(target) != 31 {
				fuck = false
			}
		}()
		time.Sleep(100 * time.Millisecond)
	}
	wg.Wait()
	log.Println("brook", fuck)
}
```

## 分析

Brook 加密协议结构如下

```
[iv][chunk][chunk]...
```

其中 `chunk` 有以下结构

```
[encrypted_length][encrypted_length_tag][encrypted_data][encrypted_data_tag]
```

Brook 加密协议的布局与 Shadowsocks AEAD 一致，可参见 https://github.com/shadowsocks/shadowsocks-rust/issues/292 （实际上 ss-rust 的缺陷是在验证 Brook 的缺陷的过程中发现）

Brook 对数据完整性的验证完全依靠 AEAD 解密过程保证——只有在第一次 AEAD 解密后，我们才能知道数据流是否伪造。如果一个服务端在发现解密失败后直接关闭连接，则可以使用 https://github.com/v2ray/v2ray-core/issues/2523 中提到的逐字节发送数据包并观测连接何时关闭的手段测量验证过程至少需要多少字节。

对于 Brook，完成验证需要接收 `iv` ，第一个 `chunk` 的 `encrypted_length` 和 `encrypted_length_tag` 。其中 `iv` 长 12 字节，`encrypted_length_tag` 因使用 AES-256-GCM ，长 16 字节，`encrypted_length` 长度为 2。显然随机数不可能通过 AEAD 解密过程的验证，服务端会在接收到完成验证所需长度的数据后关闭连接。因此当向某个开放的 TCP 端口逐字节输入随机数，连接始终在输入 12 + 16 + 2 字节后断开，则可怀疑此端口是 Brook 端口。

## 防御

按照 https://censorbib.nymity.ch/#Frolov2020a 的结论，最稳妥的防御是从不主动关闭异常的连接。我们不可能改变完成验证所需长度，但从不主动关闭连接应足以阻止此类依赖服务端响应的主动探测。

**Comment by txthinking** [comment]
I have thought about this question. What we need to know is that there are many custom protocols on the Internet. For example, as far as I know in the field of Internet of Things, programmers in the field used aes cbc to encrypt their data, but aes is different. All encryption methods have the concept of block, so if we randomly send data, we can always let the decryptor know that this is an illegal request at a certain moment and close the connection. This is normal behavior, and the sender finds that the connection is closed. I can only know that this **may** is some kind of encryption corresponding to aes, of course it may not be aes encryption, it is just a private protocol written by some strange programmers for specific places. And gcm encryption with the development of hardware In the field of IoT, more programmers are using it. (Of course there may be more areas I don’t know about, after all, the Internet is huge). So the conclusion is that it cannot be concluded that it provides proxy services behind it.

In fact, we all know the network controller, and they completely block your service because they don’t know what service you are running. For example, the Iranian government network wants to adopt this scheme recently, and the Iranian campus network probabilistically allows unknown services to continue running . And I think if the network controller adopts the first plan, it will definitely limit the development of the entire network. For them, this is not a good plan. I believe they will think carefully.

The above is my thinking.


这个问题我曾经想过, 我们需要知道的是互联网上有很多自定义协议, 比如据我所知的物联网领域, 曾经领域的程序员很流行aes cbc去加密他们的数据, 而aes下不同的加密方式都有块的概念, 所以如果我们随机发送数据, 我们总是能让解密方在某一个时刻知道这是非法请求进而关闭连接, 这是正常的行为, 而发送方发现连接被关闭, 只能知道这**可能**是aes对应的某种加密方式, 当然也可能不是aes加密, 只是某些奇怪的程序员写的私有协议用于特定的地方. 而gcm加密随着硬件的发展在物联网领域更多程序员有在使用. (当然可能还有更多我不知道的领域, 毕竟互联网很大). 所以结论是不能断定它背后提供的是代理服务.

其实我们都知道网络控制方, 完全在他们不知道你跑的什么服务下而封锁你的服务. 比如最近伊朗政府网络好想采取的就是这个方案, 而伊朗校园网则概率性允许未知服务继续运行. 而我想网络控制方如果采取了第一个方案, 一定会限制整个网络的发展, 对于他们而言这并不是一个好的方案, 我相信他们会谨慎的思考.

以上是我的思考.

**Comment by dlccontributor** [comment]
Brook is a cross-platform strong encryption and not ********detectable******** proxy.

**Comment by txthinking** [comment]
@dlccontributor Please understand the POC. The POC **ONLY** know it [**MAY**] be AES(please know again, even AES, it sill MAY), so you **CAN NOT** say Brook is **detectable**.
I will copy a simple service from our company’s IoT project to illustrate this later

**Comment by txthinking** [comment]
This is a IoT service, the POC prints it is Brook, but it is not.

```
package main

import (
        "io"
        "log"
        "net"

        "github.com/txthinking/encrypt"
)

func main() {
        l, err := net.Listen("tcp", ":6896")
        if err != nil {
                panic(err)
        }
        defer l.Close()
        for {
                c, err := l.Accept()
                if err != nil {
                        panic(err)
                }
                go func(c net.Conn) {
                        defer c.Close()
                        for {
                                // Read the air conditioner temperature
                                b := make([]byte, 30)
                                if _, err := io.ReadFull(c, b); err != nil {
                                        return
                                }
                                temperature, err := encrypt.AESGCMDecrypt(b[12:], []byte("12345678901234567890123456789012"), b[:12])
                                if err != nil {
                                        return
                                }
                                log.Println(temperature, c.RemoteAddr())
                                // Write temperature into Kafka based on device IP c.RemoteAddr().
                                // Omit, send control command to device code and more
                        }
                }(c)
        }
}
```

**Comment by txthinking** [comment]
And in out old system. (Please don't laugh at us, we no longer use it now)
The IP of many devices can be different from the factory IP, so we will have a device ID.

So this is **NO AES**, yet another IoT service,  the POC still print it is Brook, but it is really not.

```
deviceid(10) + province code(4) + agent id(2) + activation id(6) + temperature(2) + factory IP(4)
```
> In fact, the device id only has 6 digits at the beginning, changed to 10 digits a few years later

```
package main

import (
        "io"
        "net"
)

func main() {
        l, err := net.Listen("tcp", ":6896")
        if err != nil {
                panic(err)
        }
        defer l.Close()
        for {
                c, err := l.Accept()
                if err != nil {
                        panic(err)
                }
                go func(c net.Conn) {
                        defer c.Close()
                        for {
                                // deviceid(10) + provice code(4) + agent id(2) + activation id(6) + temperature(2) + factory IP(4)
                                b := make([]byte, 30)
                                if _, err := io.ReadFull(c, b); err != nil {
                                        return
                                }
                                // find deviceid from SQL Database or not found then close
                                notfounddeviceid := false
                                if !notfounddeviceid {
                                        // not a device, return
                                        return
                                }
                                if notfounddeviceid {
                                        // Write info into SQL Server
                                }
                        }
                }(c)
        }
}
```

**Comment by txthinking** [comment]
@studentmain 
In any case, we are still very grateful to you for discussing this issue, and we will still adopt your simple as an option. Even though we removed the code to close illegal connections randomly before

**Comment by txthinking** [comment]
The new commit bypassed the POC. Recheck steps:

On server
```
# Create a new Linux 64bit server
$ sudo su
$ cd /usr/local/
$ wget https://golang.org/dl/go1.15.linux-amd64.tar.gz
$ tar zxf go1.15.linux-amd64.tar.gz
$ export PATH=$PATH:/usr/local/go/bin/
$ go get -u github.com/txthinking/brook/cli/brook
$ ~/go/bin/brook server -l :80 -p 1
```

On client(POC)
```
$ go run poc.go server_ip:80
2020/08/28 12:06:39 brook false
```
