### ISSUE TITLE
Brook Client: Custom Server Name Indication and Allow Insecure Connection

### ISSUE THREAD

**Issue by aztecrabbit** [txthinking/brook#733]
I want to connect to wss server with custom server name indication and allow insecure connection

**Comment by txthinking** [comment]
I am doing this

**Comment by essoojay** [comment]
The way to go!..

**Comment by txthinking** [comment]
# brook.dev v20220401

Built at 2022-02-20

### CLI

```
nami install brook.dev
```

-   brook server
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook client
    -   Remove: --bindip
    -   Add: --socks5ServerIP
-   brook wsserver
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook wsclient
    -   Remove: --bindip
    -   Add: --socks5ServerIP
    -   Add: --address
-   brook wssserver
    -   Remove: --domain
    -   Add: --domainaddress
    -   Add: --cert
    -   Add: --certkey
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook wssclient
    -   Remove: --bindip
    -   Add: --socks5ServerIP
    -   Add: --address
    -   Add: --insecure
-   brook relayoverbrook
    -   Add: --address
    -   Add: --insecure
-   brook dns
    -   Add: --blockDomainList
    -   Add: --address
    -   Add: --insecure
-   brook tproxy
    -   Add: --blockDomainList
    -   Add: --address
    -   Add: --insecure
-   brook link
    -   Add: --name
    -   Add: --address
    -   Add: --insecure
-   brook connect
    -   Remove: --bindip
    -   Add: --socks5ServerIP
-   brook socks5
    -   Remove: --socks5
    -   Remove: --bindip
    -   Add: --listen
    -   Add: --socks5ServerIP

### GUI

-   Support extra parameter `address` with brook link
-   Support extra parameter `insecure` with brook link
-   Support Connectivity Check

**Windows: Please delete wintun.\* files in the same directory before running**

**Windows: 运行之前删除同目录下的 wintun.\* 文件们**

**If the version number has not changed after opening, because there is a cache, you can reopen it**

**如果打开后查看版本号没变，因为有缓存，重新打开下即可**

https://storage.googleapis.com/txthinking/brook/index.html

**Comment by txthinking** [comment]
v20220401
