### ISSUE TITLE
Brook-Client Socks5 Server can't bind certain IPs.

### ISSUE THREAD

**Issue by Handsome1080P** [txthinking/brook#817]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
Version: Latest one.
Command: `brook --debug client -s 111111.xyz:3269 -p 555555 --socks5 192.168.200.9:6666`

**192.168.200.9 is my server ip address which is running brook client.And I wanna use Netch or SSTAP,Tun2socks  on anther PC to forward TCP/UDP to brook- client socks5 server.But this program need socks5 server to assign binding on a certain IP for receive data,if not,the UDP not working.I checked the Brook IP binding info,I can't change it to any IP address,always "*".Like this pic below.I found Brook socks5 server have "--bindip" option but why Brook-client socks5 server no this option?**

![image.png](https://i.loli.net/2021/06/02/IacK29CQzUWnFLx.png)

The another socks5 server(gost):
![image.png](https://i.loli.net/2021/06/02/DpMvOZIujSrtP3J.png)

**Comment by txthinking** [comment]
try v20210701

**Comment by txthinking** [comment]
# brook.dev v20220401

Built at 2022-02-20

### CLI

```
nami install brook.dev
```

-   brook server
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook client
    -   Remove: --bindip
    -   Add: --socks5ServerIP
-   brook wsserver
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook wsclient
    -   Remove: --bindip
    -   Add: --socks5ServerIP
    -   Add: --address
-   brook wssserver
    -   Remove: --domain
    -   Add: --domainaddress
    -   Add: --cert
    -   Add: --certkey
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook wssclient
    -   Remove: --bindip
    -   Add: --socks5ServerIP
    -   Add: --address
    -   Add: --insecure
-   brook relayoverbrook
    -   Add: --address
    -   Add: --insecure
-   brook dns
    -   Add: --blockDomainList
    -   Add: --address
    -   Add: --insecure
-   brook tproxy
    -   Add: --blockDomainList
    -   Add: --address
    -   Add: --insecure
-   brook link
    -   Add: --name
    -   Add: --address
    -   Add: --insecure
-   brook connect
    -   Remove: --bindip
    -   Add: --socks5ServerIP
-   brook socks5
    -   Remove: --socks5
    -   Remove: --bindip
    -   Add: --listen
    -   Add: --socks5ServerIP

### GUI

-   Support extra parameter `address` with brook link
-   Support extra parameter `insecure` with brook link
-   Support Connectivity Check

**Windows: Please delete wintun.\* files in the same directory before running**

**Windows: 运行之前删除同目录下的 wintun.\* 文件们**

**If the version number has not changed after opening, because there is a cache, you can reopen it**

**如果打开后查看版本号没变，因为有缓存，重新打开下即可**

https://storage.googleapis.com/txthinking/brook/index.html

**Comment by txthinking** [comment]
v20220401
