### ISSUE TITLE
add SNI feature

### ISSUE THREAD

**Issue by HowdydotID** [txthinking/brook#856]
Hi Dev, thanks for the awesome project!
can you add the SNI feature to this project?
so can be used for various purposes

**Comment by txthinking** [comment]
more?

**Comment by essoojay** [comment]
+1

Please add SNI and allowinsecure. this very well made proxy should have global appeal. Some of us can do with SNI and allowinsecure.

**Comment by txthinking** [comment]
SNI feature means server-side or client-side?

**Comment by essoojay** [comment]
Both server and client, if implemented on server, GUI or CLI client would have entry implemented too..

**Comment by txthinking** [comment]
doing

**Comment by txthinking** [comment]
# brook.dev v20220401

Built at 2022-02-20

### CLI

```
nami install brook.dev
```

-   brook server
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook client
    -   Remove: --bindip
    -   Add: --socks5ServerIP
-   brook wsserver
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook wsclient
    -   Remove: --bindip
    -   Add: --socks5ServerIP
    -   Add: --address
-   brook wssserver
    -   Remove: --domain
    -   Add: --domainaddress
    -   Add: --cert
    -   Add: --certkey
    -   Add: --blockDomainList
    -   Add: --blockCIDR4List
    -   Add: --blockCIDR6List
    -   Add: --updateListInterval
-   brook wssclient
    -   Remove: --bindip
    -   Add: --socks5ServerIP
    -   Add: --address
    -   Add: --insecure
-   brook relayoverbrook
    -   Add: --address
    -   Add: --insecure
-   brook dns
    -   Add: --blockDomainList
    -   Add: --address
    -   Add: --insecure
-   brook tproxy
    -   Add: --blockDomainList
    -   Add: --address
    -   Add: --insecure
-   brook link
    -   Add: --name
    -   Add: --address
    -   Add: --insecure
-   brook connect
    -   Remove: --bindip
    -   Add: --socks5ServerIP
-   brook socks5
    -   Remove: --socks5
    -   Remove: --bindip
    -   Add: --listen
    -   Add: --socks5ServerIP

### GUI

-   Support extra parameter `address` with brook link
-   Support extra parameter `insecure` with brook link
-   Support Connectivity Check

**Windows: Please delete wintun.\* files in the same directory before running**

**Windows: 运行之前删除同目录下的 wintun.\* 文件们**

**If the version number has not changed after opening, because there is a cache, you can reopen it**

**如果打开后查看版本号没变，因为有缓存，重新打开下即可**

https://storage.googleapis.com/txthinking/brook/index.html

**Comment by txthinking** [comment]
v20220401
