### ISSUE TITLE
Android device with larger aspect ratios cause blank page, (Samsung S8 etc.)

### ISSUE THREAD

**Issue by ElementMTT** [txthinking/brook#89]
#### Steps to reproduce the problem
0. 首页无法显示
1. Android 7.0
2. Samsung s8+

**Comment by txthinking** [comment]
I don't ensure this is caused by missing google play. So.
if anyone encounter this problem too, please comment here and tell me:
* Have you installed google play?

**Comment by ltuxer** [comment]
s8+ blank page too
1.installed google play
2.Android 7.0
3.v20171114

**Comment by txthinking** [comment]
https://play.google.com/apps/publish/?account=5782780637672672797#ReviewDetailsPlace:p=com.txthinking.brook&reviewid=gp:AOqpTOGWZ9ZQ6_UV3fzsyzL_juQWhZrb2wIB74lfkQoT9FRRAee-E6A01Smu1O1cMH82cw-adJf4iJnX-myh0Q

**Comment by TwoBall** [comment]
play上不好回复，大概就是这样https://i.imgur.com/fzknz7q.png https://i.imgur.com/ueeCkQh.png。如果点击填充整个屏幕就是空白的。默认是填充整个屏幕的，所以是空白的

**Comment by txthinking** [comment]
From:
https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html

Samsung Galaxy S8: `18.5:9`
LG G6: `18:9`
"We recommend that you design your app to support aspect ratios of 2.1 or higher."

I think this is a bug, sorry for the trouble for you. I will continue do research.

**Comment by txthinking** [comment]
The temporary solution maybe don't let Brook fill all screen? like @TwoBall said.

**Comment by txthinking** [comment]
Can you try https://storage.googleapis.com/txthinking-file/_/tmp/app-release.apk?
And give me a response.

**Comment by ltuxer** [comment]
不是不行，只要分屏了再重新进去就正常了，如果不分屏的话还是白屏
S8+
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by txthinking** [comment]
Today, When I open Brook Android in my Pixel, Blank page appeared.
I just swipe process and open again a fews times. It show correctly.

 I don't know whether this is the same problem with Samsung screen.

I don't know why. I guess caused by firebase SDK(blocked in China), it will initialize first, if it failed then back to app.

**Comment by txthinking** [comment]
Please have a try:
https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-test-for-s8.apk

Thanks.

**Comment by ltuxer** [comment]
现在怎么样都见不到首页了，之前的切到后台还可以见到

**Comment by txthinking** [comment]
😬

**Comment by TwoBall** [comment]
使用test-s8版本，用s8的分屏模式是可以看到首页的，全屏模式还是看不到的

**Comment by txthinking** [comment]
Thanks to all.

Please have a try this no firebase version:
https://storage.googleapis.com/txthinking-file/_/tmp/brookapp-max-without-firebase.apk

**Comment by kirbyzhu** [comment]
it still does not work well.

2018年1月29日 14:32，"Cloud" <notifications@github.com>写道：

Thanks to all.

Please have a try this no firebase version:
https://storage.googleapis.com/txthinking-file/_/tmp/
brookapp-max-without-firebase.apk

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/txthinking/brook/issues/89#issuecomment-361152235>, or mute
the thread

**Comment by ltuxer** [comment]
三星内测版安卓8.0
侧栏有显示主页啥都没显示

**Comment by mfjdsg** [comment]
xiaomi6 Blank page too.

1.installed google play.
2.Android 7.1
3.v20171113

**Comment by txthinking** [comment]
Please track #138
